# Visual Acuity 

Suppose we are interested in the hypothesis that children playing outside leads them to have better eyesight.

Consider the following population of ten children whose visual acuity we can measure. 

- Visual acuity is the decimal version of the fraction given as output in standard eye exams. 
- Someone with 20/20 vision has acuity 1.0, while someone with 20/40 vision has acuity 0.5. 
- Numbers greater than 1.0 are possible for people with better than “normal” visual acuity.

```{r make visual data}
d <- data.table(
  child = 1:10, 
  y_0 = c(1.2, 0.1, 0.5, 0.8, 1.5, 2.0, 1.3, 0.7, 1.1, 1.4), 
  y_1 = c(1.2, 0.7, 0.5, 0.8, 0.6, 2.0, 1.3, 0.7, 1.1, 1.4)
)
```

In this table: 

- `y_1` means means the measured *visual acuity* if the child were to play outside at least 10 hours per week from ages 3 to 6'  
- `y_0` means the measured *visual acuity* if the child were to play outside fewer than 10 hours per week from age 3 to age 6; 
- Both of these potential outcomes *at the child level* would be measured at the same time, when the child is 6. 

1. Compute the individual treatment effect for each of the ten children.
2. Tell a "story" that could explain this distribution of treatment effects. In particular, discuss what might cause some children to have different treatment effects than others.
3. For this population, what is the true average treatment effect (ATE) of playing outside.
4. Suppose we are able to do an experiment in which we can control the amount of time that these children play outside for three years. We happen to randomly assign the odd-numbered children to treatment and the even-numbered children to control. What is the estimate of the ATE you would reach under this assignment? (Please describe your work.)
5. How different is the estimate from the truth? Intuitively, why is there a difference?
6. We just considered one way (odd-even) an experiment might split the children. How many different ways (every possible ways) are there to split the children into a treatment versus a control group (assuming at least one person is always in the treatment group and at least one person is always in the control group)?
7. Suppose that we decide it is too hard to control the behavior of the children, so we do an observational study instead. Children 1-5 choose to play an average of more than 10 hours per week from age 3 to age 6, while Children 6-10 play less than 10 hours per week. Compute the difference in means from the resulting observational data.
8. Compare your answer in (7) to the true ATE. Intuitively, what causes the difference?

